### ISSUE TITLE
Exception: gtype-struct

### ISSUE THREAD

**Issue by ezg** [dlech/gisharp#2]
Hi, I'm trying to use your code generator to create a binding for a library. 
I get the following exception. It seems like `opaque` type `gtype-struct` is not supported. I'm not very familiar with GObject , what does this mean and is there away around this? 
```
Unhandled Exception: System.Exception: Unknown opaque type 'gtype-struct'.
   at GISharp.CodeGen.Reflection.GirType.get_BaseType() in /dev/gisharp/CodeGen/Reflection/GirType.cs:line 396
   at GISharp.CodeGen.Reflection.GirType.IsSubclassOf(Type c) in /dev/gisharp/CodeGen/Reflection/GirType.cs:line 232
   at GISharp.CodeGen.Globals.IsSubclassOf[T](Type type) in /dev/gisharp/CodeGen/Globals.cs:line 64
   at GISharp.CodeGen.Globals.IsDelegate(Type type) in /dev/gisharp/CodeGen/Globals.cs:line 76
   at GISharp.CodeGen.Gir.Type.LazyGetUnmanagedType() in /dev/gisharp/CodeGen/Gir/Type.cs:line 26
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.CreateValue()
   at GISharp.CodeGen.Gir.GIType.get_UnmanagedType() in /dev/gisharp/CodeGen/Gir/GIType.cs:line 30
   at GISharp.CodeGen.Syntax.FieldExtensions.GetDeclaration(Field field) in /dev/gisharp/CodeGen/Syntax/FieldExtensions.cs:line 22
   at GISharp.CodeGen.Syntax.RecordExtensions.<>c.<GetGTypeStructClassMembers>b__13_0(Field x) in /dev/gisharp/CodeGen/Syntax/RecordExtensions.cs:line 216
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.CodeAnalysis.SyntaxList`1.InsertRange(Int32 index, IEnumerable`1 nodes)
   at GISharp.CodeGen.Syntax.RecordExtensions.GetGTypeStructClassMembers(Record record) in /dev/gisharp/CodeGen/Syntax/RecordExtensions.cs:line 215
   at GISharp.CodeGen.Syntax.NamespaceExtensions.<<GetMembers>g__getDeclarations|1_0>d.MoveNext() in /dev/gisharp/CodeGen/Syntax/NamespaceExtensions.cs:line 79
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at GISharp.CodeGen.Syntax.NamespaceExtensions.GetMembers(Namespace namespace) in /dev/gisharp/CodeGen/Syntax/NamespaceExtensions.cs:line 101
   at GISharp.CodeGen.Syntax.RepositoryExtensions.GetCompilationUnit(Repository repository) in /dev/gisharp/CodeGen/Syntax/RepositoryExtensions.cs:line 19
   at GISharp.CodeGen.MainClass.Main(String[] args) in /dev/gisharp/CodeGen/Program.cs:line 272
```

**Comment by dlech** [comment]
Hi, this repository is still very experimental, so I'm not sure how useful it is at this point in time. In fact, I just did a major overhaul of the code generator and I am afraid I broke a few things that I haven't fixed yet. This looks like one of those things that I broke.

**Comment by ezg** [comment]
Okay thanks that update!
